# This file is for DEVELOPERS of the matchmaker library.
# End-users will install RAPIDS and then 'pip install matchmaker'.
name: matchmaker-dev
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - rapids=25.08 # Pulls in the whole GPU stack for development
  - pip
  - pip:
      - -e . # Installs the local 'matchmaker' project in editable mode